In [1]:
import numpy as np
np.__version__

'1.26.3'

In [3]:
L = list(range(10))
L

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [4]:
type(L[0])

int

In [6]:
#Because of Python’s dynamic typing, we can even create heterogeneous lists
L3 = [True, "2", 3.0, 4]
[type(item) for item in L3]

[bool, str, float, int]

- 1D: vector
- 2D: matrix
- 3D: Tensor

# Create Array

In [44]:
# NumPy’s version of the operation is computed much more quickly.

In [8]:
# integer array:
# unlike Python lists, NumPy is constrained to arrays that all contain the same type. 
np.array([1, 4, 2, 5, 3])

array([1, 4, 2, 5, 3])

In [9]:
# If we want to explicitly set the data type of the resulting array, we can use the dtype keyword:
np.array([1, 2, 3, 4], dtype='float32')

array([1., 2., 3., 4.], dtype=float32)

In [10]:
# unlike Python lists, NumPy arrays can explicitly be multidimensional; here’s
# one way of initializing a multidimensional array using a list of lists:
# nested lists result in multidimensional arrays
np.array([range(i, i + 3) for i in [2, 4, 6]])

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

# Creating Arrays from Scratch

In [11]:
# Create a length-10 integer array filled with zeros
np.zeros(10, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [12]:
# Create a 3x5 floating-point array filled with 1s
np.ones((3, 5), dtype=float)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [13]:
# Create a 3x5 array filled with 3.14
np.full((3, 5), 3.14)

array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])

In [14]:
# Create an array filled with a linear sequence
# Starting at 0, ending at 20, stepping by 2
# (this is similar to the built-in range() function)
np.arange(0, 20, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [16]:
# Create an array of five values evenly spaced between 0 and 1
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [18]:
# Create a 3x3 array of uniformly distributed (توزیع یکنواخت)
# random values between 0 and 1
np.random.random((3, 3))

array([[0.26113094, 0.64949676, 0.04463768],
       [0.28205636, 0.32340442, 0.35046794],
       [0.34413891, 0.3462895 , 0.25352124]])

In [19]:
# Create a 3x3 array of normally distributed (توزیع نرمال)
# random values with mean 0 and standard deviation 1
np.random.normal(0, 1, (3, 3))

array([[0.05068835, 1.43522279, 1.22773517],
       [0.86071714, 1.25361834, 1.15824632],
       [0.03895224, 0.26113297, 0.75215533]])

In [20]:
# Create a 3x3 array of random integers in the interval [0, 10)
np.random.randint(0, 10, (3, 3))

array([[1, 0, 0],
       [0, 0, 0],
       [7, 5, 2]])

In [21]:
# Create a 3x3 identity matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [23]:
# Create an uninitialized array of three integers
# The values will be whatever happens to already exist at that
# memory location
np.empty(3)

array([1., 1., 1.])

# NumPy Standard Data Types

In [24]:
# when constructing an array, you can specify them using a string:
np.zeros(10, dtype='int16')

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int16)

In [25]:
# Or using the associated NumPy object:
np.zeros(10, dtype=np.int16)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int16)

# NumPy Array Attributes

In [27]:
np.random.seed(0) # seed for reproducibility
x1 = np.random.randint(10, size=6) # One-dimensional array
x2 = np.random.randint(10, size=(3, 4)) # Two-dimensional array
x3 = np.random.randint(10, size=(3, 4, 5)) # Three-dimensional array

In [28]:
#Each array has attributes ndim (the number of dimensions), shape (the size of each dimension), and size (the total size of the array):
print("x3 ndim: ", x3.ndim)
print("x3 shape:", x3.shape)
print("x3 size: ", x3.size)

x3 ndim:  3
x3 shape: (3, 4, 5)
x3 size:  60


In [30]:
print("dtype:", x3.dtype)
print("itemsize:", x3.itemsize, "bytes")
print("nbytes:", x3.nbytes, "bytes")

dtype: int32
itemsize: 4 bytes
nbytes: 240 bytes


# Array Indexing: Accessing Single Elements

In [35]:
x1

array([5, 0, 3, 3, 7, 9])

In [32]:
x1[0]

5

In [33]:
x1[4]

7

In [34]:
# To index from the end of the array, you can use negative indices:
x1[-1]

9

In [36]:
x2

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [37]:
x2[0, 0]

3

In [38]:
 x2[2, -1]

7

In [39]:
# modify values using any of the above index notation:
x2[0, 0] = 12

In [40]:
x2

array([[12,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])

# Array Slicing: Accessing Subarrays

1D

In [41]:
# we can use square brackets to access subarrays
# syntax : x[start:stop:step]
# If any of these are unspecified, they default to the values start=0, stop=size of dimension, step=1
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [42]:
x[:5] # first five elements

array([0, 1, 2, 3, 4])

In [43]:
x[5:] # elements after index 5

array([5, 6, 7, 8, 9])

In [44]:
x[4:7] # middle subarray

array([4, 5, 6])

In [45]:
x[::2] # every other element

array([0, 2, 4, 6, 8])

In [46]:
x[1::2] # every other element, starting at index 1

array([1, 3, 5, 7, 9])

In [47]:
x[::-1] # all elements, reversed

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [48]:
x[5::-2] # reversed every other from index 5

array([5, 3, 1])

2D

In [49]:
x2[:2, :3] # two rows, three columns

array([[12,  5,  2],
       [ 7,  6,  8]])

In [50]:
x2[:3, ::2] # all rows, every other column

array([[12,  2],
       [ 7,  8],
       [ 1,  7]])

In [51]:
x2[::-1, ::-1]

array([[ 7,  7,  6,  1],
       [ 8,  8,  6,  7],
       [ 4,  2,  5, 12]])

In [52]:
print(x2[:, 0]) # first column of x2

[12  7  1]


In [53]:
print(x2[0, :]) # first row of x2

[12  5  2  4]


In [54]:
print(x2[0]) # equivalent to x2[0, :]

[12  5  2  4]


# Subarrays as no-copy views

# Creating copies of arrays

In [4]:
x2 = np.random.randint(10, size=(3, 4)) # Two-dimensional array
print(x2)

[[3 4 5 8]
 [0 1 3 5]
 [0 2 8 4]]


In [5]:
x2_sub_copy = x2[:2, :2].copy()
print(x2_sub_copy)

[[3 4]
 [0 1]]


# Reshaping of Arrays

In [6]:
grid = np.arange(1, 10).reshape((3, 3))
print(grid)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [10]:
x = np.array([1, 2, 3, 4])

In [12]:
# row vector via reshape
x.reshape((2, 2))

array([[1, 2],
       [3, 4]])

if we don't sure what is the correct number for every dimention, we can set to -1 and it set it correctly.

# Concatenation of arrays

In [13]:
x = np.array([1, 2, 3])
y = np.array([3, 2, 1])
np.concatenate([x, y])

array([1, 2, 3, 3, 2, 1])

In [14]:
# You can also concatenate more than two arrays at once:
z = [99, 99, 99]
print(np.concatenate([x, y, z]))

[ 1  2  3  3  2  1 99 99 99]


In [15]:
 grid = np.array([[1, 2, 3],
                [4, 5, 6]])
# concatenate along the first axis
np.concatenate([grid, grid])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [16]:
# concatenate along the second axis (zero-indexed)
np.concatenate([grid, grid], axis=1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

Similarly, np.dstack will stack arrays along the third axis. => must be tuple

In [17]:
x = np.array([1, 2, 3])
grid = np.array([[9, 8, 7],
                [6, 5, 4]])
# vertically stack the arrays
np.vstack([x, grid])

array([[1, 2, 3],
       [9, 8, 7],
       [6, 5, 4]])

In [18]:
# horizontally stack the arrays
y = np.array([[99],
            [99]])
np.hstack([grid, y])

array([[ 9,  8,  7, 99],
       [ 6,  5,  4, 99]])

# Splitting of arrays

In [21]:
# pass a list of indices giving the split points
# Notice that N split points lead to N + 1 subarrays
x = [1, 2, 3, 99, 99, 3, 2, 1]
x1, x2, x3 = np.split(x, [3, 5])
print(x1, x2, x3)

[1 2 3] [99 99] [3 2 1]


In [22]:
grid = np.arange(16).reshape((4, 4))
grid

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [23]:
upper, lower = np.vsplit(grid, [2])
print(upper)
print(lower)

[[0 1 2 3]
 [4 5 6 7]]
[[ 8  9 10 11]
 [12 13 14 15]]


In [24]:
left, right = np.hsplit(grid, [2])
print(left)
print(right)

[[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]]
[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]


# Arithmetic operation (UFunctions)

In [26]:
x = np.arange(4)
print("x =", x)
print("x + 5 =", x + 5)
print("x - 5 =", x - 5)
print("x * 2 =", x * 2)
print("x / 2 =", x / 2)
print("x // 2 =", x // 2) # floor division
print("-x = ", -x)
print("x ** 2 = ", x ** 2)
print("x % 2 = ", x % 2)

x = [0 1 2 3]
x + 5 = [5 6 7 8]
x - 5 = [-5 -4 -3 -2]
x * 2 = [0 2 4 6]
x / 2 = [0.  0.5 1.  1.5]
x // 2 = [0 0 1 1]
-x =  [ 0 -1 -2 -3]
x ** 2 =  [0 1 4 9]
x % 2 =  [0 1 0 1]


# Absolute value

In [28]:
x = np.array([-2, -1, 0, 1, 2])

In [30]:
np.absolute(x)

array([2, 1, 0, 1, 2])

In [31]:
np.abs(x)

array([2, 1, 0, 1, 2])

In [32]:
# This ufunc can also handle complex data, in which the absolute value returns the magnitude:
x = np.array([3 - 4j, 4 - 3j, 2 + 0j, 0 + 1j])
np.abs(x)

array([5., 5., 2., 1.])

# Trigonometric functions

In [33]:
theta = np.linspace(0, np.pi, 3)
print("theta = ", theta)
print("sin(theta) = ", np.sin(theta))
print("cos(theta) = ", np.cos(theta))
print("tan(theta) = ", np.tan(theta))

theta =  [0.         1.57079633 3.14159265]
sin(theta) =  [0.0000000e+00 1.0000000e+00 1.2246468e-16]
cos(theta) =  [ 1.000000e+00  6.123234e-17 -1.000000e+00]
tan(theta) =  [ 0.00000000e+00  1.63312394e+16 -1.22464680e-16]


In [34]:
x = [-1, 0, 1]
print("x = ", x)
print("arcsin(x) = ", np.arcsin(x))
print("arccos(x) = ", np.arccos(x))
print("arctan(x) = ", np.arctan(x))

x =  [-1, 0, 1]
arcsin(x) =  [-1.57079633  0.          1.57079633]
arccos(x) =  [3.14159265 1.57079633 0.        ]
arctan(x) =  [-0.78539816  0.          0.78539816]


# Exponents and logarithms

In [35]:
x = [1, 2, 3]
print("x =", x)
print("e^x =", np.exp(x))
print("2^x =", np.exp2(x))
print("3^x =", np.power(3, x))

x = [1, 2, 3]
e^x = [ 2.71828183  7.3890561  20.08553692]
2^x = [2. 4. 8.]
3^x = [ 3  9 27]


In [36]:
x = [1, 2, 4, 10]
print("x =", x)
print("ln(x) =", np.log(x))
print("log2(x) =", np.log2(x))
print("log10(x) =", np.log10(x))

x = [1, 2, 4, 10]
ln(x) = [0.         0.69314718 1.38629436 2.30258509]
log2(x) = [0.         1.         2.         3.32192809]
log10(x) = [0.         0.30103    0.60205999 1.        ]


In [37]:
x = [0, 0.001, 0.01, 0.1]
print("exp(x) - 1 =", np.expm1(x))
print("log(1 + x) =", np.log1p(x))

exp(x) - 1 = [0.         0.0010005  0.01005017 0.10517092]
log(1 + x) = [0.         0.0009995  0.00995033 0.09531018]


# Aggregations: reduce

In [39]:
# calling reduce on the add ufunc returns the sum of all elements in the array:
np.add.reduce(x)

15

In [40]:
# calling reduce on the multiply ufunc results in the product of all array elements:
np.multiply.reduce(x)

120

In [41]:
# If we’d like to store all the intermediate results of the computation, we can instead use accumulate:
np.add.accumulate(x)

array([ 1,  3,  6, 10, 15])

In [42]:
np.multiply.accumulate(x)

array([  1,   2,   6,  24, 120])

# Aggregations: Sum

In [45]:
L = np.random.random(100)
L

array([1.34548690e-01, 1.34124360e-01, 3.94011804e-01, 8.89802046e-01,
       7.93973131e-01, 9.61151531e-01, 3.09441729e-01, 2.39897029e-01,
       4.58504400e-01, 4.60640227e-01, 9.34796122e-01, 1.92111106e-01,
       6.96702022e-01, 8.87560830e-02, 9.81206122e-01, 5.25996161e-01,
       4.70911385e-01, 1.93649963e-01, 5.39343105e-01, 2.05074392e-01,
       2.58588671e-01, 6.64195664e-01, 1.64427054e-01, 5.59131931e-01,
       1.85324054e-01, 9.23684514e-01, 9.95755799e-02, 6.40559088e-01,
       2.00771166e-01, 5.15527478e-02, 8.01330143e-01, 4.86496812e-01,
       3.43536954e-01, 1.42841542e-01, 8.62980533e-01, 3.77731907e-03,
       6.22045741e-03, 1.24744234e-01, 3.21531810e-01, 4.13744081e-01,
       2.31587476e-01, 8.67538293e-01, 7.33553762e-01, 8.06615043e-01,
       5.83611993e-01, 8.21017849e-01, 3.49169053e-01, 3.14236016e-01,
       5.66952194e-01, 9.30202201e-01, 9.83574152e-01, 7.09555593e-01,
       2.52079550e-01, 6.81866045e-01, 1.07375444e-01, 2.80314645e-01,
      

In [46]:
np.sum(L)

51.90195031072854

# Aggregations: Minimum and Maximum

In [47]:
np.min(L), np.max(L)

(0.0007384864615552766, 0.9893130831848365)

In [49]:
M = np.random.random((3, 4))
print(M)

[[0.49871336 0.62035575 0.52783517 0.19066029]
 [0.4865701  0.65969759 0.60728875 0.53259407]
 [0.34856617 0.92831267 0.65259234 0.55446818]]


In [50]:
# By default, each NumPy aggregation function will return the aggregate over the entire array:
M.sum()

6.607654445254948

In [51]:
# we can find the minimum value within each column by specifying axis=0:
M.min(axis=0)

array([0.34856617, 0.62035575, 0.52783517, 0.19066029])

In [52]:
# we can find the maximum value within each row:
M.max(axis=1)

array([0.62035575, 0.65969759, 0.92831267])

# Other aggregation functions

Function Name NaN-safe Version Description
np.sum        np.nansum        Compute sum of elements
np.prod       np.nanprod       Compute product of elements
np.mean       np.nanmean       Compute median of elements
np.std        np.nanstd        Compute standard deviation
np.var        np.nanvar        Compute variance
np.min        np.nanmin        Find minimum value
np.max        np.nanmax        Find maximum value
np.argmin     np.nanargmin     Find index of minimum value
np.argmax     np.nanargmax     Find index of maximum value
np.median     np.nanmedian     Compute median of elements
np.percentile np.nanpercentile Compute rank-based statistics of elements
np.any        N/A              Evaluate whether any elements are true
np.all        N/A              Evaluate whether all elements are true

# Normalize

In [2]:
a = [1 , 3]
a_mean = np.mean(a)
a_std = np.std(a)
norm_a = (a - a_mean) / a_std
norm_a

array([-1.,  1.])

# Broadcasting

In [57]:
a = np.array([0, 1, 2])
b = np.array([5, 5, 5])
M = np.ones((3, 3))
M

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [56]:
a + b

array([5, 6, 7])

In [54]:
a + 5

array([5, 6, 7])

In [58]:
a + M

array([[1., 2., 3.],
       [1., 2., 3.],
       [1., 2., 3.]])

#  standard comparison operations

In [59]:
 x = np.array([1, 2, 3, 4, 5])

In [60]:
x < 3 # less than

array([ True,  True, False, False, False])

In [61]:
x > 3 # greater than

array([False, False, False,  True,  True])

In [62]:
x <= 3 # less than or equal

array([ True,  True,  True, False, False])

In [63]:
x >= 3 # greater than or equal

array([False, False,  True,  True,  True])

In [64]:
x != 3 # not equal

array([ True,  True, False,  True,  True])

In [65]:
x == 3 # equal

array([False, False,  True, False, False])

# Counting entries

In [76]:
rng = np.random.RandomState(0)
x = rng.randint(10, size=(3, 4))
x

array([[5, 0, 3, 3],
       [7, 9, 3, 5],
       [2, 4, 7, 6]])

In [68]:
# how many values less than 6?
np.count_nonzero(x < 6)

8

In [69]:
np.sum(x < 6)

8

In [70]:
# how many values less than 6 in each row?
np.sum(x < 6, axis=1)

array([4, 2, 2])

# Any()

In [71]:
# are there any values greater than 8?
np.any(x > 8)

True

# All()

In [72]:
# are all values less than 10?
np.all(x < 10)

True

In [75]:
np.all(x < 10 , axis=1)

array([ True,  True,  True])

# Boolean operators ( AND , OR , ...)

In [ ]:
print("Number days without rain: ", np.sum(inches == 0))
print("Number days with rain: ", np.sum(inches != 0))
print("Days with more than 0.5 inches:", np.sum(inches > 0.5))
print("Rainy days with < 0.1 inches :", np.sum((inches > 0) & (inches < 0.2)))

# Masking operation

In [77]:
x

array([[5, 0, 3, 3],
       [7, 9, 3, 5],
       [2, 4, 7, 6]])

In [79]:
# to select some values from the array, we can simply index on this Boolean array; this is known as a masking operation:
x[x < 5]
# What is returned is a one-dimensional array filled with all the values that meet this condition. 

array([0, 3, 3, 3, 2, 4])

In [80]:
A = np.array([1, 0, 1, 0, 1, 0], dtype=bool)
B = np.array([1, 1, 1, 0, 1, 1], dtype=bool)
A | B

array([ True,  True,  True, False,  True,  True])

In [81]:
A or B

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

# Fancy Indexing

In [82]:
# another style of array indexing, known as fancy indexing.
# it means passing an array of indices to access multiple array elements at once. For example:
import numpy as np
rand = np.random.RandomState(42)
x = rand.randint(100, size=10)
print(x)

[51 92 14 71 60 20 82 86 74 74]


In [83]:
ind = [3, 7, 4]
x[ind]

array([71, 86, 60])

In [84]:
X = np.arange(12).reshape((3, 4))
X

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [85]:
row = np.array([0, 1, 2])
col = np.array([2, 1, 3])
X[row, col]

array([ 2,  5, 11])

# Combined Indexing

In [86]:
# We can combine fancy and simple indices:
X[2, [2, 0, 1]]

array([10,  8,  9])

In [87]:
# We can also combine fancy indexing with slicing:
X[1:, [2, 0, 1]]

array([[ 6,  4,  5],
       [10,  8,  9]])

# Sorting Arrays

In [88]:
x = np.array([2, 1, 4, 3, 5])
np.sort(x)

array([1, 2, 3, 4, 5])

In [89]:
# returns the indices of the sorted elements:
i = np.argsort(x)
print(i)

[1 0 3 2 4]


In [90]:
x[i]

array([1, 2, 3, 4, 5])

In [91]:
rand = np.random.RandomState(42)
X = rand.randint(0, 10, (4, 6))
print(X)

[[6 3 7 4 6 9]
 [2 6 7 4 3 7]
 [7 2 5 4 1 7]
 [5 1 4 0 9 5]]


In [92]:
# sort each column of X
np.sort(X, axis=0)

array([[2, 1, 4, 0, 1, 5],
       [5, 2, 5, 4, 3, 7],
       [6, 3, 7, 4, 6, 7],
       [7, 6, 7, 4, 9, 9]])

In [93]:
# sort each row of X
np.sort(X, axis=1)

array([[3, 4, 6, 6, 7, 9],
       [2, 3, 4, 6, 7, 7],
       [1, 2, 4, 5, 7, 7],
       [0, 1, 4, 5, 5, 9]])

# partition

In [94]:
# find the K smallest values in the array
# np.partition takes an array and a number K; the result is a new array with the smallest K values to the left of the partition,
# and the remaining values to the right, in arbitrary order
x = np.array([7, 2, 3, 1, 6, 5, 4])
np.partition(x, 3)

array([2, 1, 3, 4, 6, 5, 7])

In [96]:
#  use argsort function along multiple axes to find the nearest neighbors of each point in a set
X = rand.rand(10, 2)
X

array([[0.23089383, 0.24102547],
       [0.68326352, 0.60999666],
       [0.83319491, 0.17336465],
       [0.39106061, 0.18223609],
       [0.75536141, 0.42515587],
       [0.20794166, 0.56770033],
       [0.03131329, 0.84228477],
       [0.44975413, 0.39515024],
       [0.92665887, 0.727272  ],
       [0.32654077, 0.57044397]])

In [ ]:
np.argsort()
np.argpartition()

# Where

In [ ]:
np.where(df["col1"] > 0.5,
        "class A", # if condition is True
        "class B" #is condition is False)